### ISSUE TITLE
APP:  load a new a dataset clear the previous result

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattleng#105]
ideally if the app renders based on states stored in providers, we just reset each provider to the starting value

- [x] add an alert before the clear
- [x] reset Model tab
  - [x] reset wordcloud 
  - [x] reset forest
  - [x] reset tree
- [x] reset console
- [x] reset script
- [x] reset the text after the dataset button
<img width="1920" alt="Screenshot 2024-06-07 at 13 52 35" src="https://github.com/gjwgit/rattleng/assets/74629333/d17c2baa-ad16-4e07-a247-aef40b4b7dc2">

**Comment by yixiangyin** [comment]
ref.read(terminalProvider.notifier).state = Terminal();

Adding this line causes this bug. It seems that the new terminal doesn't have the library installed.
![Image](https://github.com/gjwgit/rattleng/assets/74629333/d4e02464-ad33-4b5e-b4cb-c7d18b3c61da)

**Comment by gjwgit** [comment]
May need to ensure `rStart(ref);` is run on a reset (like line 55 of `lib/app.dart`).

**Comment by gjwgit** [comment]
Is your change where you add the line `ref.read(terminalProvider.notifier).state = Terminal();` in your branch? I can't see it and so I can't try to replicate your issue.

Also though, perhaps you should no try to restart the Terminal if that is what you are wanting to do. Perhaps we can have an R script to reset all the R variables that we need to, if that was the purpose here?

**Comment by yixiangyin** [comment]
I forgot to push it. It's in my branch now. Yes I did this. It seems working. The purpose is to start fresh and clear everything that was in the console before.

**Comment by gjwgit** [comment]
Basically working. Closing now.
