### ISSUE TITLE
WORDCLOUD: Display a busy icon while the wordcloud is being built

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattleng#108]
## User story

As a user, after I tap the BUILD button in WORDCLOUD I expect to see some indication that the app is busy like a busy icon until the image is displayed or some other suitable/standard mechanism.

**Comment by gjwgit** [comment]
Do the same for Tree and Forest.

**Comment by yixiangyin** [comment]
The wordcloud one has been fixed in #148 .

**Comment by yixiangyin** [comment]
I think this issue can be closed because the circular indicator is in the image_page widget.
