### ISSUE TITLE
SCRIPT: Remember current location in the scrolled script.

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattleng#109]
## User Story

As an end user, I have scrolled through the script to find a location of interest. I then navigate to another function to have a look there and then come back to the SCRIPT only to find it is now reset to the top of the script. That is rather annoying. It should be where I left it.

**Comment by zheyxu** [comment]
Use `IndexedStack` to make it work. After switching tab, the scrollable bar still in the previous position.
![Image](https://github.com/user-attachments/assets/d02dc70a-3c5d-4c01-b505-cef9fb6ed7cf)

**Comment by gjwgit** [comment]
Want this for the SCRIPT tab not the CONSOLE (though for CONSOLE it is also okay).

On Linux the SCRIPT scroll always returns to the top on a rebuild.

From a user experience it would be nice if it was where I left it.

**Comment by zheyxu** [comment]
Hi @gjwgit, have you tested the latest change in the branch? The _**Script**_ page also works.
**On Linux the SCRIPT scroll always returns to the top on a rebuild.**
On every rebuild app, I think the page should be reset.

**Comment by zheyxu** [comment]
make qtest > qtest.tmp
integration_test/app_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/demo_dataset_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/demo_explore_correlation_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/demo_explore_missing_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/demo_explore_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/demo_explore_visual_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/demo_model_cluster_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/demo_model_nnet_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/demo_model_tree_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/demo_transform_cleanup_ignore_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/demo_transform_impute_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/explore_set_ignore_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/large_dataset_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/large_explore_correlation_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/large_explore_missing_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/large_explore_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/large_explore_visual_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/large_model_nnet_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/large_model_tree_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/large_transform_impute_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/reset_dataset_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/reset_dataset_visual_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/sherlock_dataset_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

YES

**Comment by zheyxu** [comment]
Made pr https://github.com/gjwgit/rattleng/pull/463
