### ISSUE TITLE
TREE: Implement a panel navigator with left/right arrows to view the multiple outputs.

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattleng#121]
## Description

This panel navigator widget will be the basis of all output panels in the app, with an implentation for the wordcloud/tree first.

Each page has a left and right arrow to go to the previous/next page. If there is none the arrow is greyed and not functional.

The first page is always the intro markdown explanatory page so the user can always navigate back to that page for information.

Investigate if there is an out-of-the-box widget that does this and if build one for the app.

**Comment by gjwgit** [comment]
Initial work looks great. Was this meant to be in the PR or a work in progress?

Some things to consider:

- [ ] The whole display background should be white and take up the whole lower space below the config.
- [ ] Can the arrows be floating buttons instead of taken up the whole border area just for the buttons.
- [ ] If there is only one pane to display then there should not be a second empty pane.



![Image](https://github.com/gjwgit/rattleng/assets/1681429/6364665d-0855-4ce2-a387-876b0fb0ee6a)

**Comment by yixiangyin** [comment]
This bug occurs when you switch to tree tab. Do you know what's causing the isuse?
`══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY
╞═══════════════════════════════════════════════════════════
The following assertion was thrown while applying parent data.:
Incorrect use of ParentDataWidget.
The ParentDataWidget Expanded(flex: 1) wants to apply ParentData of type
FlexParentData to a
RenderObject, which has been set up to accept ParentData of incompatible
type ParentData.
Usually, this means that the Expanded widget has the wrong ancestor
RenderObjectWidget. Typically,
Expanded widgets are placed directly inside Flex widgets.
The offending Expanded is currently placed inside a RepaintBoundary widget.
The ownership chain for the RenderObject that received the incompatible
parent data was:
  DecoratedBox ← Container ← Expanded ←
  FutureBuilder<dynamic>-[<'markdown_file'>] ← RepaintBoundary
← IndexedSemantics ← _SelectionKeepAlive ←
NotificationListener<KeepAliveNotification> ← KeepAlive ←
AutomaticKeepAlive ← ⋯

When the exception was thrown, this was the stack:
#0      RenderObjectElement._updateParentData.<anonymous closure>
(package:flutter/src/widgets/framework.dart:6545:11)
#1      RenderObjectElement._updateParentData
(package:flutter/src/widgets/framework.dart:6562:6)
#2      RenderObjectElement.attachRenderObject
(package:flutter/src/widgets/framework.dart:6605:7)
#3      RenderObjectElement.mount
(package:flutter/src/widgets/framework.dart:6467:5)
#4      SingleChildRenderObjectElement.mount
(package:flutter/src/widgets/framework.dart:6768:11)
...     Normal element mounting (13 frames)
#17     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:4340:16)
#18     Element.updateChild
(package:flutter/src/widgets/framework.dart:3843:20)
#19     ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:5512:16)
#20     StatefulElement.performRebuild
(package:flutter/src/widgets/framework.dart:5650:11)
#21     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#22     BuildOwner.buildScope
(package:flutter/src/widgets/framework.dart:2905:19)
#23     WidgetsBinding.drawFrame
(package:flutter/src/widgets/binding.dart:1136:21)
#24     RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:443:5)
#25     SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1392:15)
#26     SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart:1313:9)
#27     SchedulerBinding._handleDrawFrame
(package:flutter/src/scheduler/binding.dart:1171:5)
#28     _invoke (dart:ui/hooks.dart:312:13)
#29     PlatformDispatcher._drawFrame
(dart:ui/platform_dispatcher.dart:419:5)
#30     _drawFrame (dart:ui/hooks.dart:283:31)
════════════════════════════════════════════════════════════════════════════
════════════════════════

flutter: Selected tab: 2`

**Comment by yixiangyin** [comment]
```
return Row(
      children: [
        IconButton(
          icon: Icon(
            Icons.arrow_left,
            color: _currentPage > 0 ? Colors.black : Colors.grey,
            size: 32,
          ),
          onPressed: _currentPage > 0 ? _goToPreviousPage : null,
        ),
        Expanded(
          child: Container(
            height: 500,
            child: PageView(
              controller: _pageController,
              onPageChanged: (index) {
                setState(() {
                  _currentPage = index;
                });
              },
              children: [
                showMarkdownFile(treeIntroFile),
                Container(
                  decoration: sunkenBoxDecoration,
                  width: double.infinity,
                  padding: const EdgeInsets.only(left: 10),
                  child: SingleChildScrollView(
                    child: SelectableText(
                      content,
                      style: monoTextStyle,
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
        IconButton(
          icon: Icon(
            Icons.arrow_right,
            size: 32,
            color: _currentPage < numPages - 1
                ? Colors.black
                : Colors.grey,
                
          ),
          onPressed: _currentPage < numPages - 1
              ? _goToNextPage
              : null,
        ),
      ],
    )
```

**Comment by yixiangyin** [comment]
so I remove the container for now.
```
The following assertion was thrown during performResize():
Horizontal viewport was given unbounded height.
Viewports expand in the cross axis to fill their container and constrain
their children to match
their extent in the cross axis. In this case, a horizontal viewport was
given an unlimited amount of
vertical space in which to expand.

The relevant error-causing widget was:
  PageView
  PageView:file:///Users/yinyixiang/repo/my_rattleng/lib/panels/tree/display
  .dart:110:18

```

I add a height constraint in each child.
not working. the same error still

**Comment by gjwgit** [comment]
The current version is looking great. 

Just a overfull issue on long introductory text, like WordCloud.

**Comment by gjwgit** [comment]
In review - this is now mostly completed with the Pages() widget. Any refinements can be separate issues.
