### ISSUE TITLE
RESET: go back to dataset tab and reset sub tabs to the start

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattleng#123]
## Description

The RESET button on the top toolbar should prompt to confirm the RESET and then will return the focus to the DATASET tab and set the sub stabs within each feature to the first tab.

**Comment by yixiangyin** [comment]
return the focus to the DATASET tab will depend on issue

**Comment by yixiangyin** [comment]
It looks like we don't need to reset the sub tabs index. They are refreshed when we leave and enter.

**Comment by gjwgit** [comment]
I think this is ready to close.
