### ISSUE TITLE
MacOS: Get installer working on MacOS

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattleng#125]
# Description

Reference #215 and #218 - they are now closed and this is the main issue for MacOS install.

# To Repeat

Follow instructions at https://github.com/gjwgit/rattleng/blob/dev/installers/README.md

Download release from wget https://access.togaware.com/rattleng-dev-macos.zip

Unzip and open rattleng/rattle.app

Check the **Console** tab to see if R is running - so far it is not - but there are R commands waiting....

dataset->filename makes it freeze.

The app start freezing after dataset load because R is not getting run.  Probably a permissions issue on MacOS.

![Image](https://github.com/gjwgit/rattleng/assets/74629333/7c68eb83-3072-4c0d-977d-a3769d34b2a8)

**Comment by gjwgit** [comment]
Is this still happening?

**Comment by yixiangyin** [comment]
> Is this still happening?

Yes it just happened. I didn't see error msg in the terminal so not sure the cause still. Does it happen on linux?

**Comment by gjwgit** [comment]
See also #215.

**Comment by gjwgit** [comment]
Let's use this as the master issue for getting rattle to work on MacOS

**Comment by gjwgit** [comment]
Could we build a tiny, simple APP using the xterm package to start up a shell and see if we can get that work for a MacOS install? Thanks.

**Comment by gjwgit** [comment]
Requires R to be found in the path, but it seems on MacOS the PATH is not used - a security issue - so hard code /usr/local/bin/R for now.
