### ISSUE TITLE
MODEL CLUSTER: Add configs for KMeans

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattleng#127]
![Image](https://github.com/gjwgit/rattleng/assets/1681429/b6cbdf58-040c-4103-95e4-09214a598fc9)

**Comment by zheyxu** [comment]
Separate issue into small tasks.
Add separate files model_build_cluster_kmeans.R

**Comment by zheyxu** [comment]
integration_test/app_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/demo_dataset_ignore_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/demo_dataset_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/demo_explore_correlation_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/demo_explore_missing_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/demo_explore_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/demo_explore_visual_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/demo_model_cluster_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/demo_model_nnet_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/demo_model_tree_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/demo_transform_cleanup_ignore_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/demo_transform_impute_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/large_dataset_ignore_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/large_dataset_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/large_explore_correlation_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/large_explore_missing_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/large_explore_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/large_explore_visual_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

  YES
integration_test/large_model_nnet_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/large_model_tree_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/large_transform_impute_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/reset_dataset_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/reset_dataset_visual_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES
integration_test/sherlock_dataset_test.dart--- xcodebuild: WARNING: Using the first of multiple matching destinations:

 YES

**Comment by zheyxu** [comment]
![Image](https://github.com/user-attachments/assets/f8131e65-e519-41b4-ae50-65d270dc5368)

**Comment by gjwgit** [comment]
27 Sep 05:40:53 gjw@kadesh ~/projects/rattleng$ make qtest.tmp
make qtest > qtest.tmp
integration_test/app_test.dart YES
integration_test/demo_dataset_ignore_test.dart YES
integration_test/demo_dataset_test.dart YES
integration_test/demo_explore_correlation_test.dart YES
integration_test/demo_explore_missing_test.dart YES
integration_test/demo_explore_test.dart YES
integration_test/demo_explore_visual_test.dart YES
integration_test/demo_model_cluster_test.dart YES
integration_test/demo_model_nnet_test.dart YES
integration_test/demo_model_tree_test.dart YES
integration_test/demo_transform_cleanup_ignore_test.dart YES
integration_test/demo_transform_impute_test.dart YES
integration_test/large_dataset_ignore_test.dart YES
integration_test/large_dataset_test.dart YES
integration_test/large_explore_correlation_test.dart YES
integration_test/large_explore_missing_test.dart YES
integration_test/large_explore_test.dart YES
integration_test/large_explore_visual_test.dart YES
integration_test/large_model_nnet_test.dart YES
integration_test/large_model_tree_test.dart YES
integration_test/large_transform_impute_test.dart YES
integration_test/reset_dataset_test.dart YES
integration_test/reset_dataset_visual_test.dart YES
integration_test/sherlock_dataset_test.dart YES
