### ISSUE TITLE
TREE: Add configs

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattleng#128]
We need to configure the script that builds a decision tree with the options available in the  old version of RATTLE

![Image](https://github.com/gjwgit/rattleng/assets/1681429/602ff96e-c42d-4538-981a-f06493430f23)

**Comment by zheyxu** [comment]
Already have decision tree:



![Image](https://github.com/user-attachments/assets/34ae60a1-3027-4d6c-8edb-f3f9d1b93fd7)

**Comment by gjwgit** [comment]
We need the bunch of configurations that the old rattle had: Min Split, Max Depth, etc.

**Comment by zheyxu** [comment]
Current UI design:

![Image](https://github.com/user-attachments/assets/d2231bef-933c-4c8e-87bd-288bed5af1ce)

**Comment by gjwgit** [comment]
Looking good. 

- [x] Perhaps the the numeric entry fields need not be so wide. Make the font size a little larger and max width of 5 except for priors and loss matrix which should be 10 digits wide.
- [x] Please add tooltips for each field. They can be found in https://bitbucket.org/kayontoga/rattle/src/master/inst/etc/tooltips.xml
- [x] Limit min split (0 to Inf), max depth (1 to Inf), min bucket (1 to Inf) all integers
- [x] Limit complexity to be 0.0000 to 1.0000
- [x] Priors will be in the pattern of `0.4,0.6` adding up to 1.0 and is optional
- [x] Loss matrix must be 4 comma separated integers like `0,2,10,0` and is optional

These 'business logic' checks should be done through the interface before running the build script.

**Comment by gjwgit** [comment]
Priors and Loss Matrix **can** be empty.


![Image](https://github.com/user-attachments/assets/c9af0eef-628b-4ff8-8da0-975419150a9f)

**Comment by zheyxu** [comment]
Hi @gjwgit, need help with the modified R code for `Conditional` decision tree



![Image](https://github.com/user-attachments/assets/32ec202b-3fc0-49ba-b024-80d10643738e)

And other configuration has been done and can be check.

**Comment by zheyxu** [comment]
Made pr https://github.com/gjwgit/rattleng/pull/257
![Image](https://github.com/user-attachments/assets/2cd7178b-b898-404d-87ff-54b0f72b1cfa)
