### ISSUE TITLE
WORDCLOUD: Migrate to using vector graphics

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattleng#148]
## Description

WORDCLOUD currently generates a PNG file. Can we change this to a vector graphics file, either SVG or PDF, which ever is best supported for display and scaling in Flutter

- [x] use svg

**Comment by yixiangyin** [comment]
raw html looks good too. It shows frequency on hover.
![Image](https://github.com/gjwgit/rattleng/assets/74629333/269a573d-f744-4a02-ae77-83f6880b9d21)

**Comment by yixiangyin** [comment]
Can you remind why we want to switch to other format except to scale the image larger? It's might be better to make it zoomable @gjwgit

**Comment by yixiangyin** [comment]
the svg build up somehow after rebuild: the new one on the left, old one on the right. Go to next page and come back solved it.

![Image](https://github.com/gjwgit/rattleng/assets/74629333/1bde888e-1e45-48f5-baaa-ec150569a6f3)

**Comment by yixiangyin** [comment]
75d01a47afd51a4fc353d6666adc89655f4573e2 is the not working version. It's been fixed but I am not too sure about what's causing the error. Investigate later

**Comment by yixiangyin** [comment]
trim gives bad resolution. disable for now. might restore later in another issue
not trimmed

![Image](https://github.com/gjwgit/rattleng/assets/74629333/9dda07aa-6c61-44c0-8b8d-46d5332e6bd1)
trimmed
![Image](https://github.com/gjwgit/rattleng/assets/74629333/b2c4a037-d6cf-45a9-a4bd-00ae5e3e55eb)

**Comment by yixiangyin** [comment]
effect:
<img width="1352" alt="Screenshot 2024-07-11 at 14 21 20" src="https://github.com/gjwgit/rattleng/assets/74629333/b4c3027b-5047-4e14-a66e-396b98b55853">

**Comment by yixiangyin** [comment]
png -> svg gives better resolution.
png:
<img width="1352" alt="Screenshot 2024-07-11 at 15 51 38" src="https://github.com/gjwgit/rattleng/assets/74629333/9b7b60e9-59b0-4ea1-b635-53909fc96995">

svg:
<img width="1352" alt="Screenshot 2024-07-11 at 14 14 05" src="https://github.com/gjwgit/rattleng/assets/74629333/cb585c1a-e946-427b-9366-dfeb0ac13649">

**Comment by gjwgit** [comment]
Is there anything more required for this issue?

**Comment by yixiangyin** [comment]
> Is there anything more required for this issue?

No, it can be closed
