### ISSUE TITLE
MUTLIPLE PANELS: create a new widget

### ISSUE THREAD

**Issue by yixiangyin** [gjwgit/rattleng#162]
- [x] create this widget called pages

This widget takes a list of childrens as pages. It will be a wrapper for pageView().
if build clicked, add a new page.

- [x] refactor the wordcloud panel with this widget
- [x] refactor the tree panel with this widget
# Why?
avoid duplication of code because the same code will appear across all panels.

**Comment by yixiangyin** [comment]
I found it's hard and not clean to get the jump to result page after build working with a new widget. I came up with an alternative is to indicate the user that there are multiple pages.

**Comment by gjwgit** [comment]
Looking good. Thanks.

Yes, I think that is better - with the dots to indicate the number of pages. Please implement that.

Also, it gives more width to the display of the results.

And, let's implement a heuristic within Pages() - if there is only one page, then obviously that is displayed. If more than 1 page then by default display the second page.

And, I wonder if we also add an optional parameter `Pages(children: pages, view: 3)` to display a specific page by default?

**Comment by yixiangyin** [comment]
closed. See #184 for the UI enhancement.
