### ISSUE TITLE
BUG: dataset tab: incorrect use of ParentDataWidget

### ISSUE THREAD

**Issue by yixiangyin** [gjwgit/rattleng#164]
occur when you load demo dataset

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while looking for parent data.:
Incorrect use of ParentDataWidget.
Competing ParentDataWidgets are providing parent data to the same RenderObject:
- Expanded(flex: 1), which writes ParentData of type FlexParentData, (typically placed directly
inside a Flex widget)
- Expanded(flex: 1), which writes ParentData of type FlexParentData, (typically placed directly
inside a Flex widget)
A RenderObject can receive parent data from multiple ParentDataWidgets, but the Type of ParentData
must be unique to prevent one overwriting another.
Usually, this indicates that one or more of the offending ParentDataWidgets listed above isn't
placed inside a dedicated compatible ancestor widget that it isn't sharing with another
ParentDataWidget of the same type.
Otherwise, separating aspects of ParentData to prevent conflicts can be done using mixins, mixing
them all in on the full ParentData Object, such as KeepAlive does with KeepAliveParentDataMixin.
The ownership chain for the RenderObject that received the parent data was:
  ConstrainedBox ← Container ← Expanded ← DatasetPanel ← Expanded ← Column ←
KeyedSubtree-[GlobalKey#0236f] ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ← ⋯

When the exception was thrown, this was the stack:
#0      RenderObjectElement._debugCheckCompetingAncestors.<anonymous closure> (package:flutter/src/widgets/framework.dart:6345:11)
#1      RenderObjectElement._debugCheckCompetingAncestors (package:flutter/src/widgets/framework.dart:6392:6)
#2      RenderObjectElement._findAncestorParentDataElements.<anonymous closure> (package:flutter/src/widgets/framework.dart:6438:7)
#3      RenderObjectElement._findAncestorParentDataElements (package:flutter/src/widgets/framework.dart:6445:6)
#4      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:6603:68)
#5      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6467:5)
#6      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6768:11)
...     Normal element mounting (13 frames)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340:16)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3843:20)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#22     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#24     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2905:19)
#25     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1136:21)
#26     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:5)
#27     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
#28     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:9)
#29     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1035:9)
#30     PlatformDispatcher.scheduleWarmUpFrame.<anonymous closure> (dart:ui/platform_dispatcher.dart:837:16)
#34     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 3 frames from class _Timer and dart:async-patch)
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by gjwgit** [comment]
Removed the Expanded and working. What consequences? Some more Overflows? We'll see, test, resolve.
