### ISSUE TITLE
TESTING: Implement integration testing

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattleng#166]
## Description

Flutter provides an extensive testing framework.

Each push/commit then depends on the tests completing correctly, using githooks.

This task is to implement the testing framework for Rattle.

**Comment by junhaow1** [comment]
(base) kev@Junhaos-MacBook-Pro rattleng %     git push --set-upstream origin kev/166_integration
Enter passphrase for key '/Users/kev/.ssh/id_ed25519': 
Running Flutter integration tests...
Using device: macos
00:00 +0: loading /Users/kev/dev/rattle_graham/rattleng/integration_test/app_test.dart                                                                                                 B
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006000-0016090121D8801E, name:My Mac }
{ platform:macOS, arch:x86_64, id:00006000-0016090121D8801E, name:My Mac }
00:21 +0: loading /Users/kev/dev/rattle_graham/rattleng/integration_test/app_test.dart                                                                                                 
✓ Built build/macos/Build/Products/Debug/rattle.app
00:22 +0: Counter increments smoke test                                                                                                                                                
R START:                'main.R'
PAGES: pageController: length: 1
00:23 +1: All tests passed!                                                                                                                                                            
Tests passed. Proceeding with push.
Enumerating objects: 136, done.
Counting objects: 100% (111/111), done.
Delta compression using up to 10 threads
Compressing objects: 100% (66/66), done.
Writing objects: 100% (82/82), 12.65 KiB | 12.65 MiB/s, done.
Total 82 (delta 52), reused 21 (delta 13), pack-reused 0
remote: Resolving deltas: 100% (52/52), completed with 19 local objects.
remote: 
remote: Create a pull request for 'kev/166_integration' on GitHub by visiting:
remote:      https://github.com/gjwgit/rattleng/pull/new/kev/166_integration
remote: 
To github.com:gjwgit/rattleng.git
 * [new branch]      kev/166_integration -> kev/166_integration
branch 'kev/166_integration' set up to track 'origin/kev/166_integration'.

**Comment by junhaow1** [comment]
![Image](https://github.com/user-attachments/assets/4e63c719-d08c-49e0-b90c-23ec223ebef9)

**Comment by junhaow1** [comment]
> Created a pre-push hook and Added the testing script to the pre-push hook

#!/bin/sh
echo "Running Flutter integration tests..."

# Get a list of connected devices
devices=$(flutter devices --machine | jq -r '.[].id')

# Filter out the iOS device
device_id=$(echo "$devices" | grep -v '00008110-000435310242801E' | head -n 1)

# Default to macOS if no other device is found
if [ -z "$device_id" ]; then
  device_id="macos"
fi

echo "Using device: $device_id"

# Run Flutter integration tests on the selected device
flutter test integration_test -d $device_id

# Check if the tests passed
if [ $? -ne 0 ]; then
  echo "Tests failed. Push aborted."
  exit 1
fi

echo "Tests passed. Proceeding with push."
exit 0

**Comment by junhaow1** [comment]
Hi @gjwgit  Please note that the pre-push file is saved in the .git/hooks folder, so it is not uploaded to the repository. We need to set this up on each of our local machines. I will work on implementing this in the CI/CD workflow later.

**Comment by gjwgit** [comment]
- [x] Give a walk through of what's been done
- [x] Let's discuss what this (hooks folder) means.
- [ ] `make itest` versus `make test` - will both be useful eventually or just itest?

**Comment by junhaow1** [comment]
pre-push file is saved in the .git/hooks folder
Git hooks are scripts that Git automatically runs before or after certain events, such as committing or pushing code.  

https://github.com/user-attachments/assets/5ff92bab-2085-4a0e-bd14-796e611e6435

**Comment by gjwgit** [comment]
Let's go with the initial simple framework you have set up for now.
