### ISSUE TITLE
BUG: PathNotFoundException after rebuild

### ISSUE THREAD

**Issue by yixiangyin** [gjwgit/rattleng#169]
Happen in betwen rebuild (it disappears later)

![Image](https://github.com/gjwgit/rattleng/assets/74629333/3b7b1806-64a7-4b59-8015-c373b5a46b82)

**Comment by gjwgit** [comment]
Yes I see the same. Seems like the file has not been written yet - you might need to check how to check for file existing and finished being written to before trying to load it. I added some such code to try to fix that earlier. This seems to have started happening after moving to Pages? I wonder what might have triggered it.

**Comment by gjwgit** [comment]
Seems to be okay now.
