### ISSUE TITLE
LOG: Embed Markdown on left panel

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattleng#2]
## Description

The current left panel (under the current `Save Log` button) displays `assets/markdown/log_intro.md` as a text file. This should be updated to display it as Markdown().

![Image](https://github.com/gjwgit/rattleng/assets/1681429/0809ba98-3a25-4228-8a4a-60ee40564347)

## Why

So that the text is properly formatted according to the markdown

## Closing Criteria

- [ ] Left info panel of the LOG tab is rendered as markdown

**Comment by mukundsrinivasb** [comment]
![image](https://github.com/gjwgit/rattleng/assets/14166083/4ad1c573-96f9-4da6-85b7-be9a0c435a96)
I have set up flutter and `flutter doctor -v` is happy. I am unable to find the wdgets.dart file

**Comment by gjwgit** [comment]
My oversight. It is there now. Thanks for letting me know.

**Comment by mukundsrinivasb** [comment]
When I run `main.dart` , I get the following error .
![image](https://github.com/gjwgit/rattleng/assets/14166083/0fd377e9-acdb-4084-b705-f04ad5d82ca2)
Upon asking ChatGPT for help, I get to know that  `runner.exe.manifest` needs to be defined. 

From what I understand about `CmakeLists.txt` , cmake generates makefiles that can be run for different configurations. Is there another file where the path to `runner.exe.manifest` has been defined and has to be referenced from within the `CmakeLists.txt`?

**Comment by gjwgit** [comment]
Are you on Windows @mukundsrinivasb. I think this is a Windows specific thing. Does running the following help?

```
flutter config --enable-windows-desktop
```

or even

```
flutter create --platforms=windows,macos,linux .
```

**Comment by gjwgit** [comment]
Also, what does 'when I run run main.dart' mean. From the command line this would be

```
flutter run -d windows
```

**Comment by mukundsrinivasb** [comment]
`flutter create --platforms=windows,macos,linux .` worked for me . Thanks a lot !

**Comment by mukundsrinivasb** [comment]
![image](https://github.com/gjwgit/rattleng/assets/14166083/823b8cef-aeff-4849-af6f-e823a52de1fd)
I get the above error and I do not know how to change the imports . I have tried changing the path to absolute path

**Comment by gjwgit** [comment]
You seem to have set up your folders incorrectly. I suspect you ran the flutter create . in the lib folder, but it should have been run in the root folder. The root folder is where your should run all the flutter commands like `flutter run -d windows`, which is why your use with `package:rattle/...` etc are not working.

**Comment by mukundsrinivasb** [comment]
**I have changed the imports back and I have got it to work**
![image](https://github.com/gjwgit/rattleng/assets/14166083/574a15b7-487b-40ed-a83f-c5262527245d)

**Comment by gjwgit** [comment]
That's good. I have already removed the killall so that should not be a problem any more for Windows. The lib folder should only contain the dart source code, not the linux/ios/windows etc folders.

**Comment by mukundsrinivasb** [comment]
![image](https://github.com/gjwgit/rattleng/assets/14166083/4763890f-daa3-49df-bd68-05fa86783f1b)
This is the rendered markdown.

I shall test it with other elements of markdown such as Headings and lists

**Comment by gjwgit** [comment]
Looks good. Thanks @mukundsrinivasb. I can't merge the PR due to the multiple lib folders (and apparently 67 files that were changed - see the info for the PR), but I've used your suggested MarkdownBody() in the main branch. You may need to start with a new clone or fork.

**Comment by mukundsrinivasb** [comment]
I shall do the needful and find the next issue that is a bit more challenging
