### ISSUE TITLE
CONSOLE: Embed terminal inside the Console tab for R interaction

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattleng#26]
# Description

https://pub.dev/packages/xterm

Add an xterm into the TERM tab, and send commands to start up R and then to send R commands to the terminal and to retrieve the output from the terminal. 

The xterm is running under the Console tab but because of the way flutter rebuilds widgets, each time the tab is visited a new instance of xterm is created. Instead there should be a single instance, and each time the tab is visited it should that one instance. Then send strings to the xterm to have then run in R and read the output from the xterm to parse and load into the app.

# Why

So that a user can interact with R within the app and can also see the commands and output there as they are run.

# Closing Criteria

- [x] The TERM tab contains a terminal
- [x] The terminal is running R
- [x] One can interact with the terminal (e.g., `ls`)
- [x] Send R commands from DATA tab to the terminal to load `rattle::weather`
- [x] Get the output from R commands into the DATA tab

It will look something like:

![image](https://github.com/gjwgit/rattleng/assets/1681429/5cec57b7-4ac5-4087-bf8b-2dd900698db8)

**Comment by gjwgit** [comment]
From the repository see the example app, but in main.dart replace the various shells with just R!

```
String get shell {
    return 'R';
}
```

**Comment by mukundsrinivasb** [comment]
Is this a good issue to take up after the previous one ?

**Comment by gjwgit** [comment]
Yes, this would be a good one to work on. It is rather core to getting the communications between flutter and R working. Currently I am using an R process to send commands to R, but not yet getting results from R (see #36). It would however be nice to have this embedded console and to demonstrate sending commands to it and obtaining the output from it into flutter.

**Comment by gjwgit** [comment]
WIP - all but extracting the data is functional. Should not be too hard to extract the data.

**Comment by gjwgit** [comment]
Completed.
