### ISSUE TITLE
SCRIPT: Implement the PARAMETER mapping

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattleng#32]
# Description

This has to be implemented as an extra argument to rSource(). The concept is that the R scripts that we have available will have some parameters in the script that are set through the GUI. These are identified in the scripts as, for example, `VAR_TARGET` in data_template.R. The current rSource() has a bunch of these hard coded. This task is to take another parameter in the function which is some kind of key list, like {'VAR_TARGET': 'rain_tomorrow', ...} and in the dart code we read the text from the R script file, do the transformation then run the script and write the script to the log in the SCRIPT tab. 

This task is specifically to handle the mapping.

# Why

So that the R scripts can be generic, and are tuned through parameters that will be set in the interface.

# Acceptance Criteria

**Comment by mukundsrinivasb** [comment]
I would like to contribute to this issue as it would teach me on interfacing with `R` from flutter

**Comment by gjwgit** [comment]
Change to my thinking how this will be implemented. The parameters will now be captured through the current rattle state (the RattleModel). This is now in progress so this specific task is no longer required.
