### ISSUE TITLE
DATASET: Allow input of dataset in text bar and loaded when Enter is pressed

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattleng#52]
# Description

The current text bar where the user can type in a dataset name is not fully functional.

A user should be able to type in `rattle::weather` and then press `ENTER` to have the dataset loaded (if it is found). Similarly, typing in a path to a CSV file.

![Image](https://github.com/gjwgit/rattleng/assets/1681429/c183092a-1b2f-4e70-9ccc-87cfcdec9358)

# Why

So that the user can simply type the name of a dataset rather than navigating the GUI for a better experience and options.

# Closing Criteria

- [x] The text bar renders text in the correct order!
- [x] On pressing `ENTER` and recognising a package name syntax `package:dataset` check and load into `ds`
- [x] On pressing `ENTER` and recognising a csv filename syntax `....dataset.csv` check and load into `ds`
- [x] Anything else on a `ENTER` pops up an error message.

**Comment by zheyxu** [comment]
Support text input:
<img width="1243" alt="Screenshot 2024-08-01 at 3 06 29 AM" src="https://github.com/user-attachments/assets/18e8acc6-eab5-422e-baae-875ca20d9453">

![Image](https://github.com/user-attachments/assets/698993d7-eeb0-4c50-aa1d-f4d9496cd6d8)

**Comment by zheyxu** [comment]
Made pr https://github.com/gjwgit/rattleng/pull/225
