### ISSUE TITLE
DATASET TAB: Add variable role selection to the dataset table display

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattleng#58]
# Description

Consider the **Dataset** tab with the data displayed as below.

![Image](https://github.com/gjwgit/rattleng/assets/1681429/cfc27f46-2738-449e-b8f3-b35329ec4a17)

For each row (variable) in the table we want to include a drop down menu to choose the role of the variable like the original rattle. Choose a drop down menu, radio buttons, or maybe a toggle bar would be nice? Perhaps a drop down will take least space.

![Image](https://github.com/gjwgit/rattleng/assets/1681429/ceb78444-60d9-4813-9fe0-a14599c4fec2)

The roles are: Input, Target, Identifier, Weight, Risk, Ignore.

The default for most will be Input.

Update the dataset state with these choices.

# Why

So that a user can choose roles for each variable.

# Closing Criteria

    // TODO yyx 20240703 create a list of row. Each row contains a column name, datatype, choicechip and some content in order.

**Comment by gjwgit** [comment]
See also #64

**Comment by mukundsrinivasb** [comment]
I have made preliminary changes to building a dataset widget based on this rough sketch.
![PXL_20231116_043022049](https://github.com/gjwgit/rattleng/assets/14166083/0134f8ee-45f5-4835-87d9-24127fe7a579)

Currently the widget looks like 
![image](https://github.com/gjwgit/rattleng/assets/14166083/a4c1cfba-70bc-48cd-8886-b88e7b606fb7)

The challenges for tomorrow would be:
1. an R script to fetch the column names
2. A way to convert these columns into a row widget

**Comment by gjwgit** [comment]
Thanks @mukundsrinivasb. Something like that. 

You can get the column names from the `names(ds)` part of the stdout that is already present - see how the `glimpse()` output is extracted from the stdout text. Then you can create a dart list of strings from that text. 

Then decide in the GUI how to specify the target (a single variable), the risk (if any, a single variable) and the ident (if any, multiple variables), and the ignore (if any, multiple variables), and the wieght (if any, single variable), and the input (essentially all the rest). It can be like how it was done in the original rattle, or ideas for a nice new way of  doing so would be great too.

I would like to also see the output of the `glimpse(ds)` in some form so I can decide the different roles.

**Comment by mukundsrinivasb** [comment]
The changes to the dataset tab are based on this plan.

![PXL_20231117_075958469](https://github.com/gjwgit/rattleng/assets/14166083/d97cb3b0-d36c-45fd-be49-5261e9f482a4)

**Currently**, it looks like 

https://github.com/gjwgit/rattleng/assets/14166083/0a371d15-0c59-4f76-80fa-e04371bb2422

**Questions**
1. Is this design suitable for the use case? Specifically, does it align with the requirement that users can only assign one role to a variable?
2. Seeking clarification on the distinction between "Input" and "Weight." Can a variable be assigned both roles simultaneously, or are they mutually exclusive?

**Issues to work on over 18th and 19th of November**

1. Implement a stateful widget to handle the change in the dropdown value.
2. find a way to interface with `glimpse(ds)` using regex.

**Comment by gjwgit** [comment]
Design looks good.

A variable can not be both a weight and input.

There can only be, at most, one weight.

For regexp see the code in `lib/r` with some examples extracting the data.

**Comment by mukundsrinivasb** [comment]
**Solved Issue**
Implemented a `StateFulWidget` to handle the change in variable type.
Uploading implement_Stateful.mp4…

**Issue to be solved**
1. Interface with R to fetch the column names

**Comment by mukundsrinivasb** [comment]
**Interfaced with the R command line to get the variable names.**

**A demo of the current status of the dataset tab is given below: **
https://github.com/gjwgit/rattleng/assets/14166083/157aede7-b3a2-454c-a749-d114f818dbbd

**Things to do before Saturday**
1. Implement a scrollable widget to make the dataset tab scrollable.
2. Modify `extract_vars.dart` in order to extract the variable names without artefacts.

**Comment by gjwgit** [comment]
The video looks great so far. Thanks.

**Comment by gjwgit** [comment]
Did you have a branch where this is available to try?

**Comment by mukundsrinivasb** [comment]
The recent commits are made to
 https://github.com/mukundsrinivasb/rattleng which is a fork of the original repo. 

I shall commit to the parent repository to keep a consistent record of the changes.

**Comment by mukundsrinivasb** [comment]
https://github.com/gjwgit/rattleng/assets/14166083/defa01e8-03be-45a2-9533-7a1cb769e975

The types of the variables has been fetched however , there is a lag between when the dataset is loaded and parsing types. In order to solve the same , the following questions have to be answered :

1. Does this issue exist in the previous implementation where the types were not being fetched from the console?
2. Should the parsing of the variables be implemented asynchronously?

**Comment by gjwgit** [comment]
> The recent commits are made to https://github.com/mukundsrinivasb/rattleng which is a fork of the original repo.
> 
> I shall commit to the parent repository to keep a consistent record of the changes.

Thanks @mukundsrinivasb. Perhaps you can create a PR against my rattleng repository and I can then review the PR there.

**Comment by mukundsrinivasb** [comment]
The PR referenced above shows the current state of the DATASET tab as referenced in the video

> Implement_Types.mp4 
> The types of the variables has been fetched however , there is a lag between when the dataset is loaded and parsing types. In order to solve the same , the following questions have to be answered :
> 
> 1. Does this issue exist in the previous implementation where the types were not being fetched from the console?
> 2. Should the parsing of the variables be implemented asynchronously?

**Comment by gjwgit** [comment]
Needs a review and design work.

**Comment by yixiangyin** [comment]
![Image](https://github.com/gjwgit/rattleng/assets/74629333/1162bf70-e20a-4cd0-9a23-49cbfb0a7677)

**Comment by gjwgit** [comment]
Looks great. Thanks.
