### ISSUE TITLE
wordcloud

### ISSUE THREAD

**Issue by yixiangyin** [gjwgit/rattleng#75]
issues with wordcloud:

- [x] 1. display text when load a txt file, not using the csv script 

- [x] 2. save button for word cloud picture to save it to anywhere specified

- [x] 3. make picture scrollable (otherwise it overflows)

- [x] 4. use riverpod to rebuild the widget. display “no model has been implemented yet” and change to png after building png

**Comment by yixiangyin** [comment]
issue 1 after.
<img width="1065" alt="Screenshot 2024-03-27 at 22 57 56" src="https://github.com/gjwgit/rattleng/assets/74629333/70b62351-c233-4aa6-b20f-439b504e60fb">

**Comment by yixiangyin** [comment]
issue 2 before and after:
<img width="912" alt="Screenshot 2024-03-27 at 22 53 36" src="https://github.com/gjwgit/rattleng/assets/74629333/3b90a2cb-6baa-4204-be2e-eeae06bf2189">
<img width="912" alt="Screenshot 2024-03-27 at 22 54 29" src="https://github.com/gjwgit/rattleng/assets/74629333/8fe75455-8c8d-4e54-bde7-f2e2f7f3eb50">

**Comment by gjwgit** [comment]
Thanks for the updates. The wordcloud looks great. Here's a few suggestions:

- [ ] From your current branch yyx/75_wordcloud I still get an overflow.
- [ ] Add a button to do stop work removal to the text for the wordcloud https://survivor.togaware.com/datascience/remove-english-stop-words.html
- [ ] Add a RELOAD button that reloads the file while it is worked out how to update the page when a new image is created
- [ ] On first time when the image file is not available make the space the the image a fixed size rather than just an no height box
- [ ]

**Comment by yixiangyin** [comment]
- [ ]  From your current branch yyx/75_wordcloud I still get an overflow.
- [ ] The temporary image file should be saved into the system tmp folder rather than assets/images locally
- [ ] Perhaps remove the temporary image file on exit from the app so a new one is generated with the new data next time we run the app? This needs to be fixed as I keep getting the old one shown when I load in new data.
- [ ] Add a button to do stop word removal to the text for the wordcloud as in https://survivor.togaware.com/datascience/remove-english-stop-words.html
- [ ] Add a RELOAD button that reloads the file while it is worked out how to update the page when a new image is created
- [ ] On first time when the image file is not available make the space for the image a fixed size rather than just an no height box - i.e., don't have the Save button at the top when no image is show. From a user experience point of view it is better always down below the space where the image will go.
- [ ] What other options are available for building the wordcloud, and add them to the page. I picture a collection of options (checkboxes etc) along the top of the page, above where the image will go) Things like min freq, max words, random.order, random.color, remove stop words, remove punctuation, stemming, etc. See https://cran.r-project.org/web/packages/wordcloud/wordcloud.pdf
- [ ] An option to load a second file for the word cloud comparison functionality of the package.
- [ ] When a new file is loaded under Dataset reset the "Model" to remove the current wordcloud.

**Comment by yixiangyin** [comment]
Regarding saving file to system temp folder, we might need to figure out a way to do that in R. I just realise we could get the tmp folder path in flutter and "pass" that path to R for it to create a png.

**Comment by gjwgit** [comment]
I think we have completed much of this functionality and merged into dev. Thanks @yixiangyin. 

Other separate issues created for the fine tuning now.

Move to In Review and consider closing next review meeting.
