### ISSUE TITLE
UI: convert radio buttons to tabs

### ISSUE THREAD

**Issue by yixiangyin** [gjwgit/rattleng#79]
under the model tab
<img width="2032" alt="Screenshot 2024-05-02 at 20 09 45" src="https://github.com/gjwgit/rattleng/assets/74629333/c2cb8189-009f-4bd1-95f1-b2eb9bda8a66">
hoping it's a better UI.

**Comment by gjwgit** [comment]
This has been merged into dev. Thanks for the work to do this.

Can be closed next review meeting.
