### ISSUE TITLE
BUG: refresh when switching to model tab

### ISSUE THREAD

**Issue by yixiangyin** [gjwgit/rattleng#80]
The bug happens if go to Model tab, select wordcloud radio button and go to other tab and go back, the wordcloud radio button is not selected anymore. The state of model tab should preserve.

This reason is that by default, the tab will be refreshed every time we are switching to it. As a child, ModelRadioButtons also get refreshed, always gets the default 2 (corresponds to Tree) radio button selected.
```
flutter: ModelTab rebuild
flutter: ModelRadioButtons rebuild
```

**Comment by gjwgit** [comment]
This is no longer an issue on moving to the tabbar interface.

Can be closed next meeting.
