### ISSUE TITLE
STYLE: wordcloud config bar

### ISSUE THREAD

**Issue by yixiangyin** [gjwgit/rattleng#83]
<img width="912" alt="Screenshot 2024-05-09 at 12 55 57" src="https://github.com/gjwgit/rattleng/assets/74629333/b1a5d402-9603-43ac-9fff-5077b2d7d03d">

- [x] make the text box smaller with container (scaling)
- [ ] make the configuration bar fixed at the top

**Comment by gjwgit** [comment]
I think I have done the first task - make the textbox smaller? See latest dev.

For the second one I have created a new issue

**Comment by gjwgit** [comment]
Move this to in review and then close at next meeting.
