### ISSUE TITLE
WORDCLOUD: Add Textual summary of data

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattleng#94]
## Description

- [x] The wordcloud functionality generates word frequency. Add a new results pane to display this by taping on the right side arrow. Then tap the left side arrow to return to the vizualisation.

See #121 as well for the same and more explanation of the panel navigoator concept but for the TREE tab.

another seperate issue:
The toolbar SAVE context will export a CSV file with two columns, the word, and its frequency.

**Comment by yixiangyin** [comment]
Some work needs to be before this. I have done them in a seperate issue #159 .

**Comment by gjwgit** [comment]
Added the word freq Page.
